# Generated by Django 3.0.4 on 2020-04-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddres',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='useraddres',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
