# Generated by Django 3.0.4 on 2020-03-31 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=120)),
                ('cpu', models.CharField(max_length=120)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSd'), ('NVMe', 'NVMe')], max_length=20)),
                ('screen_size', models.CharField(choices=[('14', '14'), ('15.6', '15.6'), ('17', '17')], max_length=20)),
                ('screen_resolution', models.CharField(choices=[('768', '768'), ('1080', '1080'), ('1440', '1440')], max_length=20)),
                ('screen_panel', models.CharField(choices=[('TN', 'TN'), ('VA', 'VA'), ('IPS', 'IPS')], max_length=20)),
                ('refresh', models.CharField(choices=[('60', '60'), ('120', '120'), ('144', '144')], max_length=20)),
                ('ram', models.CharField(choices=[('8', '8'), ('16', '16'), ('32', '32')], max_length=20)),
                ('gpu', models.CharField(max_length=120)),
                ('gpu_ram', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
