# Generated by Django 3.0.4 on 2020-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200331_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], max_length=20),
        ),
    ]
