# Generated by Django 3.0.4 on 2020-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(default='Win 10', max_length=20),
        ),
    ]
