# Generated by Django 3.0.4 on 2020-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_laptop_ram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='gpu_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
